name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: github action checkout
        uses: actions/checkout@v3

      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:all
